name: LotManager
main: de.bangl.lm.LotManagerPlugin
description: WorldGuard extension to manage lots/cities.
version: 1.9

authors: [ BangL ]
depend: [ WorldGuard, Vault ]
softdepend: [ WorldEdit, Essentials ]

commands:
  getlot:
    usage: /<command> [lotname] (world)
    permission: lotmanager.getlot
  lotprice:
    usage: /<command> [lotname] (world)
    permission: lotmanager.getlot
  mylot:
    usage: /<command>
    permission: lotmanager.mylot
    aliases: [ mylots ]
  lotgroupupdate:
    usage: /<command> [lotgroupname] [limit] [lot_price]
    permission: lotmanager.groupupdate
  lotgroupdefine:
    usage: /<command> [lotgroupname] [limit] [lot_price]
    permission: lotmanager.groupdefine
  lotgroupundefine:
    usage: /<command> [lotgroupname]
    permission: lotmanager.groupundefine
  lotupdate:
    usage: /<command> [lotname] [lotgroup] (world)
    permission: lotmanager.update
  lotdefine:
    usage: /<command> [lotname] [lotgroup] (world)
    permission: lotmanager.define
  lotundefine:
    usage: /<command> [lotname] (world)
    permission: lotmanager.undefine
  clearlot:
    usage: /<command> [lotname] (world)
    permission: lotmanager.clearlot
  haslot:
    usage: /<command> [username]
    permission: lotmanager.haslot
    aliases: [ haslots ]
  listlots:
    usage: /<command>
    permission: lotmanager.list
  listlotgroups:
    usage: /<command>
    permission: lotmanager.list
  savelots:
    usage: /<command>
    permission: lotmanager.savelots
  reloadlots:
    usage: /<command>
    permission: lotmanager.reloadlots
  inactivelots:
    usage: /<command>
    permission: lotmanager.inactivelots
  allocatelot:
    usage: /<command> [lotname] [playername] (world)
    permission: lotmanager.allocatelot

permissions:
  lotmanager.*:
    default: false
    children:
      lotmanager.getlot: true
      lotmanager.mylot: true
      lotmanager.groupupdate: true
      lotmanager.groupdefine: true
      lotmanager.groupundefine: true
      lotmanager.update: true
      lotmanager.define: true
      lotmanager.undefine: true
      lotmanager.clearlot: true
      lotmanager.haslot: true
      lotmanager.list: true
      lotmanager.savelots: true
      lotmanager.reloadlots: true
      lotmanager.inactivelots: true
      lotmanager.allocatelot: true
      lotmanager.sign.create: true
  lotmanager.getlot:
    default: true
    children:
      lotmanager.mylot: true
  lotmanager.mylot:
    default: true
  lotmanager.haslot:
    default: true
  lotmanager.groupupdate:
    default: op
  lotmanager.groupdefine:
    default: op
  lotmanager.groupundefine:
    default: op
  lotmanager.update:
    default: op
  lotmanager.define:
    default: op
  lotmanager.undefine:
    default: op
  lotmanager.clearlot:
    default: op
  lotmanager.list:
    default: op
  lotmanager.savelots:
    default: op
  lotmanager.reloadlots:
    default: op
  lotmanager.allocatelot:
    default: op
  lotmanager.inactivelots:
    default: op
  lotmanager.sign.create:
    default: op
    
