name: LotManager
main: de.bangl.lm.LotManagerPlugin
description: WorldGuard extension to manage lots/cities.
version: '${project.version}'

authors: [ BangL ]
depend: [ WorldGuard, Vault ]
softdepend: [ WorldEdit, Essentials ]

commands:
  lot:
    permission: lotmanager.user
    description: Allgemeiner Grundstueck-befehl. Schreibe /lot fuer weitere hilfe.
    usage: |
           Grundstueckverwaltung:
           /<command> get - Zum naechsten freien Grundstueck teleportieren
           /<command> get [Lotname] (Welt) - Grundstueck kaufen
           /<command> price [Lotname] (Welt) - Grundstueckpreis sehen
           /<command> home - Eigene Adresse anzeigen lassen
           /<command> has [Name] - Adresse eines anderen Spielers anzeigen lassen
           /<command> tphome (Welt) - Zum eigenen Grundstueck teleportieren
  lotgroup:
    permission: lotmanager.admin
    description: Lotgruppen-Administration. Schreibe /lotgroup fuer weitere hilfe.
    usage: |
           Usage:
           /<command> define [lotgroupname] [limit] [lot_price] - Neue Grundstueck-Gruppe definieren
           /<command> redefine [lotgroupname] [limit] [lot_price] - Limit und/oder Preis einer Gruppe aendern
           /<command> undefine [lotgroupname] - Gruppe loeschen
           /<command> list - Alle Gruppen auflisten
  lotadmin:
    aliases: [ lotmanager, lm ]
    permission: lotmanager.admin
    description: Lot-Administration. Schreibe /lotadmin fuer weitere hilfe.
    usage: |
           Usage:
           /<command> define [lotname] [lotgroup] (world) - Neues Grundstueck definieren
           /<command> redefine [lotname] [lotgroup] (world) - Gruppe aendern
           /<command> undefine [lotname] (world) - Grundstuecksdaten loeschen
           /<command> reload - Alle Grundstuecksdaten neu laden
           /<command> save - Alle Grundstuecksdaten abspeichern
  lotmod:
    aliases: []
    permission: lotmanager.mod
    description: Lot-Moderation. Schreibe /lotmod fuer weitere hilfe.
    usage: |
           Usage:
           /<command> clear [lotname] (world) - Alle Owner/Member eines Grundstuecks entfernen
           /<command> list - Alle Grundstuecke auflisten
           /<command> inactive - Alle inaktiv genutzen Grundstuecke auflisten
           /<command> allocate [lotname] [playername] (world) - Grundstueck zuweisen
permissions:
  lotmanager.*:
    default: false
    children:
      lotmanager.admin: true
  lotmanager.admin:
    default: false
    children:
      lotmanager.user: true
      lotmanager.mod: true
  lotmanager.user:
    default: true
    children:
      lotmanager.user.get: true
      lotmanager.user.get.default: true
      lotmanager.user.home: true
      lotmanager.user.has: true
      lotmanager.user.tp: true
      lotmanager.user.sign.seen: true
  lotmanager.mod:
    default: false
    children:
      lotmanager.mod.clear: true
      lotmanager.mod.list: true
      lotmanager.mod.inactive: true
      lotmanager.mod.allocate: true
      lotmanager.user.get.*: true
  lotmanager.admin:
    default: false
    children:
      lotmanager.admin.update: true
      lotmanager.admin.define: true
      lotmanager.admin.undefine: true
      lotmanager.admin.group.update: true
      lotmanager.admin.group.define: true
      lotmanager.admin.group.undefine: true
      lotmanager.admin.group.list: true
      lotmanager.admin.sign.create: true
      lotmanager.admin.sign.break: true
      lotmanager.admin.save: true
      lotmanager.admin.reload: true
  lotmanager.user.get:
    default: true
  lotmanager.user.get.default:
    default: true
  lotmanager.user.get.*:
    default: op
  lotmanager.user.home:
    default: true
  lotmanager.user.has:
    default: true
  lotmanager.user.tp:
    default: true
  lotmanager.user.sign.seen:
    default: op
  lotmanager.mod.clear:
    default: op
  lotmanager.mod.list:
    default: op
  lotmanager.mod.inactive:
    default: op
  lotmanager.mod.allocate:
    default: op
  lotmanager.admin.update:
    default: op
  lotmanager.admin.define:
    default: op
  lotmanager.admin.undefine:
    default: op
  lotmanager.admin.group.update:
    default: op
  lotmanager.admin.group.define:
    default: op
  lotmanager.admin.group.undefine:
    default: op
  lotmanager.admin.group.list:
    default: op
  lotmanager.admin.sign.create:
    default: op
  lotmanager.admin.sign.break:
    default: op
  lotmanager.admin.save:
    default: op
  lotmanager.admin.reload:
    default: op